[package]
name = "cozyui"
version = "0.1.0"
edition = "2024"

[dependencies]
alacritty_terminal = "0.26.0"
deunicode = "1"
phf = { version = "0.11", features = ["macros"] }
png = "0.17"
serde_json = "1"
x11rb = { version = "0.13", features = ["allow-unsafe-code"] }
xkbcommon = { version = "0.8", default-features = false, features = ["x11"] }
