// Generated by tools/export_pixel_font.py from Pixolde-Italic.ttf.
// units_per_pixel=64, range=U+0020..U+007E
use crate::bitmap_font::FontSpec;

pub const PIXOLDE_ITALIC_ATLAS_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/assets/pixolde_italic_ascii.png"
);
pub const PIXOLDE_ITALIC_CELL_W: usize = 11;
pub const PIXOLDE_ITALIC_CELL_H: usize = 15;
pub const PIXOLDE_ITALIC_COLS: usize = 16;
pub const PIXOLDE_ITALIC_X_ORIGIN: usize = 1;
#[rustfmt::skip]
pub const PIXOLDE_ITALIC_ADVANCE: [u8; 128] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 3, 5, 9, 7, 9, 9, 3, 5, 5, 6, 5, 3, 4, 2, 5, 7, 4, 7, 7, 7, 7, 6, 7, 7, 6, 3, 3, 6, 7, 6, 7, 9, 9, 8, 8, 9, 8, 8, 9, 9, 5, 7, 8, 7, 9, 9, 9, 8, 9, 8, 8, 8, 8, 8, 10, 9, 8, 8, 5, 3, 5, 6, 6, 3, 7, 8, 7, 7, 7, 7, 8, 8, 4, 4, 7, 4, 10, 8, 7, 8, 8, 8, 7, 5, 7, 8, 10, 7, 7, 8, 5, 3, 5, 7, 0];

pub const PIXOLDE_ITALIC_SPEC: FontSpec = FontSpec {
    atlas_path: PIXOLDE_ITALIC_ATLAS_PATH,
    cell_w: PIXOLDE_ITALIC_CELL_W,
    cell_h: PIXOLDE_ITALIC_CELL_H,
    cols: PIXOLDE_ITALIC_COLS,
    x_origin: PIXOLDE_ITALIC_X_ORIGIN,
    advance: &PIXOLDE_ITALIC_ADVANCE,
};
