// Generated by tools/export_vector_font.py from RozhaOne-Regular.ttf.
// pixel_size=48, range=U+0020..U+007E
use crate::bitmap_font::FontSpec;

pub(crate) const ROZHA_ONE_48_ATLAS_PATH: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/assets/rozha_one_48_ascii.png");
pub(crate) const ROZHA_ONE_48_CELL_W: usize = 69;
pub(crate) const ROZHA_ONE_48_CELL_H: usize = 85;
pub(crate) const ROZHA_ONE_48_COLS: usize = 16;
pub(crate) const ROZHA_ONE_48_X_ORIGIN: usize = 13;
#[rustfmt::skip]
pub(crate) const ROZHA_ONE_48_ADVANCE: [u8; 128] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 15, 13, 25, 27, 31, 42, 9, 16, 16, 16, 24, 14, 13, 13, 13, 28, 19, 26, 26, 26, 25, 27, 23, 26, 27, 13, 13, 24, 23, 24, 22, 48, 31, 29, 27, 30, 27, 26, 30, 32, 16, 24, 31, 25, 38, 29, 30, 28, 33, 31, 27, 28, 30, 31, 45, 30, 30, 26, 13, 13, 13, 17, 26, 26, 27, 27, 25, 29, 25, 21, 27, 31, 16, 16, 30, 16, 47, 31, 28, 28, 28, 24, 23, 18, 30, 26, 40, 28, 27, 25, 14, 7, 14, 24, 0];

pub(crate) const ROZHA_ONE_48_SPEC: FontSpec = FontSpec {
    atlas_path: ROZHA_ONE_48_ATLAS_PATH,
    cell_w: ROZHA_ONE_48_CELL_W,
    cell_h: ROZHA_ONE_48_CELL_H,
    cols: ROZHA_ONE_48_COLS,
    x_origin: ROZHA_ONE_48_X_ORIGIN,
    advance: &ROZHA_ONE_48_ADVANCE,
};
