pub(crate) enum EditKey {
    Insert(char),
    Backspace,
    Enter,
    Escape,
    Tab,
    Left,
    Right,
    None,
}

pub(crate) fn edit_key(keycode: u8, state: u16) -> EditKey {
    let shift = state & 1 != 0;
    match (keycode, shift) {
        (9, _) => EditKey::Escape,
        (22, _) => EditKey::Backspace,
        (23, _) => EditKey::Tab,
        (36, _) => EditKey::Enter,
        (65, _) => EditKey::Insert(' '),
        (113, _) => EditKey::Left,
        (114, _) => EditKey::Right,
        (10, false) => EditKey::Insert('1'),
        (10, true) => EditKey::Insert('!'),
        (11, false) => EditKey::Insert('2'),
        (11, true) => EditKey::Insert('@'),
        (12, false) => EditKey::Insert('3'),
        (12, true) => EditKey::Insert('#'),
        (13, false) => EditKey::Insert('4'),
        (13, true) => EditKey::Insert('$'),
        (14, false) => EditKey::Insert('5'),
        (14, true) => EditKey::Insert('%'),
        (15, false) => EditKey::Insert('6'),
        (15, true) => EditKey::Insert('^'),
        (16, false) => EditKey::Insert('7'),
        (16, true) => EditKey::Insert('&'),
        (17, false) => EditKey::Insert('8'),
        (17, true) => EditKey::Insert('*'),
        (18, false) => EditKey::Insert('9'),
        (18, true) => EditKey::Insert('('),
        (19, false) => EditKey::Insert('0'),
        (19, true) => EditKey::Insert(')'),
        (20, false) => EditKey::Insert('-'),
        (20, true) => EditKey::Insert('_'),
        (21, false) => EditKey::Insert('='),
        (21, true) => EditKey::Insert('+'),
        (24, false) => EditKey::Insert('q'),
        (24, true) => EditKey::Insert('Q'),
        (25, false) => EditKey::Insert('w'),
        (25, true) => EditKey::Insert('W'),
        (26, false) => EditKey::Insert('e'),
        (26, true) => EditKey::Insert('E'),
        (27, false) => EditKey::Insert('r'),
        (27, true) => EditKey::Insert('R'),
        (28, false) => EditKey::Insert('t'),
        (28, true) => EditKey::Insert('T'),
        (29, false) => EditKey::Insert('y'),
        (29, true) => EditKey::Insert('Y'),
        (30, false) => EditKey::Insert('u'),
        (30, true) => EditKey::Insert('U'),
        (31, false) => EditKey::Insert('i'),
        (31, true) => EditKey::Insert('I'),
        (32, false) => EditKey::Insert('o'),
        (32, true) => EditKey::Insert('O'),
        (33, false) => EditKey::Insert('p'),
        (33, true) => EditKey::Insert('P'),
        (34, false) => EditKey::Insert('['),
        (34, true) => EditKey::Insert('{'),
        (35, false) => EditKey::Insert(']'),
        (35, true) => EditKey::Insert('}'),
        (38, false) => EditKey::Insert('a'),
        (38, true) => EditKey::Insert('A'),
        (39, false) => EditKey::Insert('s'),
        (39, true) => EditKey::Insert('S'),
        (40, false) => EditKey::Insert('d'),
        (40, true) => EditKey::Insert('D'),
        (41, false) => EditKey::Insert('f'),
        (41, true) => EditKey::Insert('F'),
        (42, false) => EditKey::Insert('g'),
        (42, true) => EditKey::Insert('G'),
        (43, false) => EditKey::Insert('h'),
        (43, true) => EditKey::Insert('H'),
        (44, false) => EditKey::Insert('j'),
        (44, true) => EditKey::Insert('J'),
        (45, false) => EditKey::Insert('k'),
        (45, true) => EditKey::Insert('K'),
        (46, false) => EditKey::Insert('l'),
        (46, true) => EditKey::Insert('L'),
        (47, false) => EditKey::Insert(';'),
        (47, true) => EditKey::Insert(':'),
        (48, false) => EditKey::Insert('\''),
        (48, true) => EditKey::Insert('"'),
        (49, false) => EditKey::Insert('`'),
        (49, true) => EditKey::Insert('~'),
        (51, false) => EditKey::Insert('\\'),
        (51, true) => EditKey::Insert('|'),
        (52, false) => EditKey::Insert('z'),
        (52, true) => EditKey::Insert('Z'),
        (53, false) => EditKey::Insert('x'),
        (53, true) => EditKey::Insert('X'),
        (54, false) => EditKey::Insert('c'),
        (54, true) => EditKey::Insert('C'),
        (55, false) => EditKey::Insert('v'),
        (55, true) => EditKey::Insert('V'),
        (56, false) => EditKey::Insert('b'),
        (56, true) => EditKey::Insert('B'),
        (57, false) => EditKey::Insert('n'),
        (57, true) => EditKey::Insert('N'),
        (58, false) => EditKey::Insert('m'),
        (58, true) => EditKey::Insert('M'),
        (59, false) => EditKey::Insert(','),
        (59, true) => EditKey::Insert('<'),
        (60, false) => EditKey::Insert('.'),
        (60, true) => EditKey::Insert('>'),
        (61, false) => EditKey::Insert('/'),
        (61, true) => EditKey::Insert('?'),
        _ => EditKey::None,
    }
}
